apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: wallet-service
      config:
        import: optional:configserver:http://config-server.fintech.svc.cluster.local:8889
    
    user-service:
      url: http://user-service.fintech.svc.cluster.local:8080/api/users
    
    eureka:
      client:
        serviceUrl:
          defaultZone: http://discovery-service.fintech.svc.cluster.local:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true