apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service-config
  namespace: fintech
data:
  application.yml: |
    spring:
      application:
        name: wallet-service
      config:
        import: optional:configserver:http://10.0.0.237:8889
      datasource:
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    user-service:
      url: http://10.0.0.202:8090/api/users

    eureka:
      client:
        serviceUrl:
          defaultZone: http://10.0.1.176:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: when-authorized
          probes:
            enabled: true