apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: ${ECR_REGISTRY}/${IMAGE_NAME}:${DOCKER_BUILD_NUMBER}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: wallet-service-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            # MySQL Credentials
            - name: SPRING_DATASOURCE_PRIMARY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PRIMARY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            # PostgreSQL Credentials
            - name: SPRING_DATASOURCE_SECONDARY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_SECONDARY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10