apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: fintech
type: Opaque
stringData:
  username: "mysql"
  password: "password"
  database: "wallet_service_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: fintech
type: Opaque
stringData:
  username: "postgres"
  password: "password"
  database: "wallet_service_db"